#!/bin/bash

python3 simulator.py --player_1 random_agent --player_2 chantal_test_agent

if[ $1 == "gpt" ]; then
    python3 simulator.py --player_1 gpt_greedy_corners_agent --player_2 chantal_test_agent
fi
