from .random_agent import RandomAgent
from .human_agent import HumanAgent
from .student_agent import StudentAgent
from .gpt_greedy_corners_agent import StudentAgent
from .minimax_ab import Minimax_with_alpha_beta_pruning
from .chantal_test_agent import TestAgent
from .minimax import MiniMax
from .test_agent import TestAgent
from .student_agent2 import StudentAgent